name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build macOS app
        run: |
          set -e
          xcodebuild \
            -project "ml-fastvlm/app/FastVLM.xcodeproj" \
            -scheme "FastVLM App" \
            -configuration Release \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            build
