name: CI (iOS)

on:
  workflow_dispatch:

jobs:
  build-ios-simulator:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Xcode env
        run: |
          xcodebuild -version
          xcode-select -p
          xcodebuild -showsdks || true
      - name: Build iOS (Simulator, generic destination)
        run: |
          set -euo pipefail
          xcodebuild \
            -project "ml-fastvlm/app/FastVLM.xcodeproj" \
            -scheme "FastVLM App" \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            build
