name: CI (iOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios-simulator:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Xcode env
        run: |
          xcodebuild -version
          xcode-select -p
          xcrun simctl list devices | head -n 30

      - name: Build iOS (Simulator)
        run: |
          set -euo pipefail
          xcodebuild \
            -project "ml-fastvlm/app/FastVLM.xcodeproj" \
            -scheme "FastVLM App" \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            build | xcpretty || exit ${PIPESTATUS[0]}
